### PR TITLE
 Update metadata in activity.info

### PR DESCRIPTION
**Pull request by vipulgupta2048**
**Updated following parameters**
`url`, `license`, `repository`, `tags`
Removed `service_name`
Does anyone know much about this activity. As it doesn't have a help page. I can't determine what the summary would be? 

Added .gitignore file.
Will be adding Screenshots soon.

### CODE REVIEW

**Comment by quozl** [comment]
http://activities.sugarlabs.org/en-US/sugar/addon/4204 gives a good summary and description; you do have access to the metadata stored in ASLOv1, right?

Main program is GPLv3+, it is only the trivial setup that is GPLv2+.  Please set the license to `GPLv3+;GPLv2+`.

Please add COPYING for GPLv3 as file COPYING, and COPYING.GPLv2 for GPLv2.

Continue with screenshots, assuming you can make it work.  :grin:

**Comment by vipulgupta2048** [comment]
@quozl No, I don't have access to the metadata. But I do know `crtl + c` and `crtl + v`, thanks.
Roger that on other changes. I think the thing happened. I did take the screenshots already, forgot to push them.

**Comment by quozl** [comment]
Thanks.  Reviewed to db83855.

* [ ] _summary_ should be on one line.

**Comment by vipulgupta2048** [comment]
@quozl Changes made, Ready to launch. :fireworks:

**Pull request merged**
